### ISSUE TITLE
Allure with Android Instrumentation tests

### ISSUE THREAD

**Issue by kirillzh** [allure-framework/allure1#862]
Is there a way to run Android Instrumentation tests (using Espresso or Robotium) with Allure? Does it require custom adapter?

Here is related post on StackOverflow: https://stackoverflow.com/questions/28647107/allure-to-generate-reports-for-android-tests-how.

**Comment by kirillzh** [comment]
Tried to run tests with this runner: 
```java
public class AllureTestRunner extends AndroidJUnit4ClassRunner {
  public AllureTestRunner(Class<?> klass) throws InitializationError {
    super(klass, new AndroidRunnerParams(InstrumentationRegistry.getInstrumentation(), new Bundle(), false, 0, false));
  }

  public AllureTestRunner(Class<?> klass, AndroidRunnerParams runnerParams) throws InitializationError {
    super(klass, runnerParams);
  }

  @Override
  public void run(RunNotifier notifier) {
    // JUnit don't support Java SPI for adding test listeners.
    // To add global Listener we should manually create JUnitCore.
    // With gradle we don't have (?) such option.
    // Solution - add listener via runner.
    // And manually call "runStarted" and "runFinished" events.
    notifier.addListener(new AllureRunListener());

    // Allure do nothing on testRunStarted
    // Just for consistency.
    notifier.fireTestRunStarted(Description.createSuiteDescription("Tests"));

    super.run(notifier);

    // Allure don't use Result from JUnit.
    // It gathers results on its own.
    // So, basically any param is OK here.
    notifier.fireTestRunFinished(new Result());
  }
}
```

It's the same runner as [AllureTestRunner.java from allure-gradle-junit-example](https://github.com/allure-examples/allure-gradle-junit-example/blob/master/src/test/java/ru/yandex/qatools/allure/junit/AllureTestRunner.java) project but it extends `AndroidJUnit4ClassRunner`.

Logs:
```
nitoringInstrumentation  I  Instrumentation Started!
                         I  Setting context classloader to 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.test-2/base.apk", zip fil
                            e "/data/app/com.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test-2/lib/x86_64, /data/app/com.example-1/lib/x86_6
                            4, /vendor/lib64, /system/lib64]]]', Original: 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.test-2/ba
                            se.apk", zip file "/data/app/com.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test-2/lib/x86_64, /data/app/com.example-1/lib/x86_64, /vendor/lib64, /system/lib64]]]'
                         I  No JSBridge.
             InfraTrack  D  Tracking disabled due to lack of internet permissions
UsageTrackerFacilitator  I  Usage tracking disabled
           TestExecutor  D  Adding listener android.support.test.internal.runner.listener.LogRunListener
                         D  Adding listener android.support.test.internal.runner.listener.InstrumentationResultPrinter
                         D  Adding listener android.support.test.internal.runner.listener.ActivityFinisherRunListener
             TestRunner  I  run started: 1 tests
                         I  failed: null
                         I  ----- begin exception -----
                         I  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
                         I      at ru.qatools.properties.converters.ConverterManager.registerDefaults(ConverterManager.java:63)
                         I      at ru.qatools.properties.converters.ConverterManager.<init>(ConverterManager.java:42)
                         I      at ru.qatools.properties.converters.ConverterManager.<init>(ConverterManager.java:34)
                         I      at ru.qatools.properties.PropertyLoader.<init>(PropertyLoader.java:40)
                         I      at ru.qatools.properties.PropertyLoader.newInstance(PropertyLoader.java:408)
                         I      at ru.yandex.qatools.allure.Allure.<init>(Allure.java:57)
                         I      at ru.yandex.qatools.allure.Allure.<clinit>(Allure.java:37)
                         I      at ru.yandex.qatools.allure.junit.AllureRunListener.<init>(AllureRunListener.java:31)
                         I      at com.example.AllureTestRunner.run(AllureTestRunner.java:37)
                         I      at org.junit.runners.Suite.runChild(Suite.java:128)
                         I      at org.junit.runners.Suite.runChild(Suite.java:27)
                         I      at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                         I      at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                         I      at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                         I      at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                         I      at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                         I      at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                         I      at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                         I      at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                         I      at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                         I      at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                         I      at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
                         I  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Path" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.test-2/base.apk", zip file "/data/app/com.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test-2/lib/x86_64, /data/app/com.example-1/lib/x86_64, /vendor/lib64, /system/lib64]]
                         I      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                         I      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                         I      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                         I      ... 22 more
                         I      Suppressed: java.lang.ClassNotFoundException: java.nio.file.Path
                         I          at java.lang.Class.classForName(Native Method)
                         I          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                         I          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                         I          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                         I          ... 23 more
                         I      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
                         I  ----- end exception -----
                         I  failed: Test mechanism
                         I  ----- begin exception -----
                         I  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putString(java.lang.String, java.lang.String)' on a null object reference
                         I      at android.support.test.internal.runner.listener.InstrumentationResultPrinter.reportFailure(InstrumentationResultPrinter.java:177)
                         I      at android.support.test.internal.runner.listener.InstrumentationResultPrinter.testFailure(InstrumentationResultPrinter.java:167)
                         I      at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
                         I      at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
                         I      at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
                         I      at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
                         I      at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
                         I      at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
                         I      at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
                         I      at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                         I      at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                         I      at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                         I      at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                         I      at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
                         I  ----- end exception -----
```

**Comment by kirillzh** [comment]
Seems like Allure uses `java.nio.file.Paths` which doesn't exist in Android ([see](https://developer.android.com/reference/packages.html) Android packages).
![screen shot 2016-10-10 at 1 37 08 pm](https://cloud.githubusercontent.com/assets/5660531/19250363/b163218c-8eee-11e6-94bf-eabdf0e39bd8.png)


Related post on SO: https://stackoverflow.com/questions/23638181/noclassdeffounderror-on-android.

**Comment by kirillzh** [comment]
I guess there is no other solution besides replacing `java.nio.file` methods with `java.io`, is there?

**Comment by baev** [comment]
@kirillzh sorry for the delay.

> I guess there is no other solution besides replacing java.nio.file methods with java.io, is there?

I guess so. We will fix the issue in next version of adaptor

**Comment by kirillzh** [comment]
@baev, no problem, thanks for replying! 

I [tried](https://github.com/kirillzh/allure-core/commit/522831264ed477b15c75b05834542f50c3644e9a) to do that, but I'm not sure how to get rid of [Files.copy](https://github.com/allure-framework/allure-core/blob/6d8a48e47d83425b43a3ffa945f5a2680a655f69/allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/io/ReportWriter.groovy#L94) and [Files.readAllBytes](https://github.com/allure-framework/allure-core/blob/6d8a48e47d83425b43a3ffa945f5a2680a655f69/allure-commandline/src/main/java/ru/yandex/qatools/allure/command/ReportGenerate.java#L102).

**Comment by kirillzh** [comment]
Supporting Android is gonna be harder than I thought. Now it complains about `java.lang.management` package which is used in `AnnotationManager.java`.

**Comment by baev** [comment]
It is feel like we need to create separate adaptor for Android. Please consider to create an issue in https://github.com/allure-framework/allure-java/issues
