### ISSUE TITLE
java.lang.NullPointerException when running "allure generate" from command line

### ISSUE THREAD

**Issue by ndimer** [allure-framework/allure1#951]
Hi,

I installed allure-commnad-line via npm and tried to run "allure generate <results folder location>". I got this exception when running the command:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke method value() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
        at ru.yandex.qatools.allure.data.utils.PluginUtils.update(PluginUtils.groovy:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:51)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin$_process_closure1.doCall(TotalPlugin.groovy:26)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin$_process_closure1.doCall(TotalPlugin.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:109)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.access$400(GroovyCategorySupport.java:65)
        at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:249)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.use(DefaultGroovyMethods.java:403)
        at org.codehaus.groovy.runtime.dgm$755.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:248)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin.process(TotalPlugin.groovy:25)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin.process(TotalPlugin.groovy)
        at ru.yandex.qatools.allure.data.plugins.PluginManager.process(PluginManager.groovy:84)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:68)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
        at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
        at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
        at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)

I am using Java 1.8 32 bit.

Please advice how to resolve the error?

Thanks,
Nahum

**Comment by AntoineTheb** [comment]
Same results here.
Report data comes from WebdriverIO Allure Reporter: https://github.com/webdriverio/wdio-allure-reporter
OS: Arch Linux
Java: java-8-openjdk/jre

**Comment by ehborisov** [comment]
@AntoineTheb we know about that issue, but the problem is in the data that you feed to the Allure. One of the test cases probably has missing or unexpected status value. Could you please share results files with us somewhere?

**Comment by just-boris** [comment]
@AntoineTheb also you can just try to switch to Allure2

For the webdriver.io mirgation will be seamless, no need to change anything in your code.

**Comment by AntoineTheb** [comment]
@ehborisov Thank you for your fast response. I cannot share the test results unfortunately, but I can confirm that the report generator does work when no test fail. I will investigate further with the WebdriverIO team. 

@just-boris I will look into it, thank you.

**Comment by AntoineTheb** [comment]
As a heads-up, updating to `allure-commandline@2.0.0` seems to have fixed the problem.
