### ISSUE TITLE
 java.lang.NoClassDefFoundError: io/airlift/command/Cli

### ISSUE THREAD

**Issue by mlotfi2005** [allure-framework/allure1#972]
Hi, 
This is my first day trying to learn allure, I got this exception, can you please help , 

java -jar allure-cli-1.3.5.jar C:\Tests\Allure RSpec\results
Exception in thread "main" java.lang.NoClassDefFoundError: io/airlift/command/Cli
        at ru.yandex.qatools.allure.AllureCli.main(AllureCli.java:24)
Caused by: java.lang.ClassNotFoundException: io.airlift.command.Cli
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

Thanks,

**Comment by baev** [comment]
plz use allure2 instead. See https://docs.qameta.io/allure/#_installing_a_commandline

**Comment by mlotfi2005** [comment]
I did 
rspec reporting_spec.rb

it created a results folder with screenshots , now I need to do 
java -jar allure-cli-1.3.5.jar C:\Tests\Allure RSpec\results

which jar file should I use from allure2 ?
Thanks,
